#!/usr/bin/env python3
"""Tests for the strict, structural Homebrew cask normalizer."""

from __future__ import annotations

import re

from normalize_homebrew_cask import CaskNormalizationError, normalize_cask_text


SAMPLE = '''# This file was generated by GoReleaser. DO NOT EDIT.
cask "harness-lint" do
  version "1.2.3"

  on_macos do
    on_intel do
      sha256 "intel-macos"
      url "https://example.invalid/harness-lint_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "arm-macos"
      url "https://example.invalid/harness-lint_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "intel-linux"
      url "https://example.invalid/harness-lint_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "arm-linux"
      url "https://example.invalid/harness-lint_#{version}_linux_arm64.tar.gz"
    end
  end

  name "harness-lint"
  desc "Description"
  homepage "https://example.invalid"
end
'''


def main() -> int:
    normalized = normalize_cask_text(SAMPLE)
    assert normalized.count('on_arm do') == 2
    assert normalized.count('on_intel do') == 2
    assert re.search(
        r"on_macos do.*on_arm do.*on_intel do.*  end\n  on_linux do",
        normalized,
        re.DOTALL,
    )
    assert re.search(r"on_linux do.*on_arm do.*on_intel do.*\n  end", normalized, re.DOTALL)
    linux_start = normalized.index('  on_linux do')
    separator = normalized[
        normalized.rfind("  end", 0, linux_start) + len("  end") : linux_start
    ]
    assert separator == "\n"
    assert 'version "1.2.3"' in normalized
    for marker in ('arm-macos', 'intel-macos', 'arm-linux', 'intel-linux'):
        assert marker in normalized
    assert normalize_cask_text(normalized) == normalized

    try:
        normalize_cask_text(SAMPLE.replace('    on_arm do\n', '', 1))
    except CaskNormalizationError:
        pass
    else:
        raise AssertionError("missing architecture stanza was accepted")

    print("Homebrew cask normalizer tests passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
